export const CONNECT_WALLET = "CONNECT_WALLET";
export const DISCONNECT = "DISCONNECT";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_PROFILE_CARD_ADDRESS = "UPDATE_PROFILE_CARD_ADDRESS";