export const CONNECT_WALLET = "CONNECT_WALLET";
export const DISCONNECT = "DISCONNECT";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_PROFILE_CARD_ADDRESS = "UPDATE_PROFILE_CARD_ADDRESS";
export const UPDATE_PROFILE_SEARCH = "UPDATE_PROFILE_SEARCH";
export const GET_ADMIN_ROLE = "GET_ADMIN_ROLE";