export const projectCategories = [
  { key: "AG", value: "Agriculture", text: "Agriculture" },
  {
    key: "ART",
    text: "Arts & Entertainment",
    value: "Arts & Entertainment",
  },
  { key: "AUT", text: "Automotive", value: "Automotive" },
  {
    key: "BEA",
    text: "Beauty & Personal Care",
    value: "Beauty & Personal Care",
  },
  { key: "CON", text: "Construction", value: "Construction" },
  { key: "CNS", text: "Consulting", value: "Consulting" },
  { key: "EDU", text: "Education", value: "Education" },
  { key: "ENR", text: "Energy", value: "Energy" },
  { key: "EGR", text: "Engineering", value: "Engineering" },
  { key: "ENV", text: "Environment", value: "Environment" },
  { key: "FIN", text: "Finance", value: "Finance" },
  { key: "FOD", text: "Food & Beverage", value: "Food" },
  { key: "GAM", text: "Gaming", value: "Gaming" },
  { key: "GOV", text: "Government", value: "Government" },
  { key: "HEA", text: "Healthcare", value: "Healthcare" },
  { key: "HOS", text: "Hospitality", value: "Hospitality" },
  { key: "INS", text: "Insurance", value: "Insurance" },
  { key: "LAW", text: "Legal", value: "Legal" },
  { key: "MAN", text: "Manufacturing", value: "Manufacturing" },
  {
    key: "ADV",
    text: "Marketing & Advertising",
    value: "Marketing & Advertising",
  },
  { key: "NON", text: "Nonprofit", value: "Nonprofit" },
  { key: "PHA", text: "Pharmaceuticals", value: "Pharmaceuticals" },
  { key: "REA", text: "Real Estate", value: "Real Estate" },
  { key: "RET", text: "Retail", value: "Retail" },
  { key: "SER", text: "Services", value: "Services" },
  {
    key: "SPO",
    text: "Sports & Recreation",
    value: "Sports & Recreation",
  },
  {
    key: "TEC",
    text: "Technology",
    value: "Technology",
  },
  {
    key: "TEL",
    text: "Telecommunications",
    value: "Telecommunications",
  },
  {
    key: "TRA",
    text: "Transportation & Logistics",
    value: "Transportation & Logistics",
  },
  {
    key: "TOU",
    text: "Travel & Tourism",
    value: "Travel & Tourism",
  },
  { key: "OTH", text: "Other", value: "Other" },
];
